#!/bin/bash
#SBATCH --time 24:00:00     # Time requested to run the job (format hours:minutes:seconds or days-hours:minutes)
#SBATCH --job-name=structure  # Job name
#SBATCH --nodes=1        # Number of nodes to allocate. Same as SBATCH -N
#SBATCH --ntasks=1       # Number of cores to allocate. Same as SBATCH -n
#SBATCH --account=coa_jdu282_brazil_bootcamp2023  # Project allocation account name; use coa_jdu282_brazil_bootcamp2023
#SBATCH --partition=normal
#SBATCH --mem=1g
#SBATCH -e ./err/%x.%j.err  # Error file for this job.
#SBATCH -o ./out/%x.%j.out  # Output file for this job.

export PATH=$PATH:/pscratch/jdu282_brazil_bootcamp2023/programs/structure_kernel_src/

